const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('bazar', {
  runtime: {
    platform: process.platform,
    /** Suscripción electron: cambios de cuentas desde otra ventana deben refrescar widgets dependientes. */
    subscribeCuentasChanged: (listener) => {
      if (typeof listener !== 'function') return () => {}
      const handler = () => listener()
      ipcRenderer.on('bazar:cuentas-changed', handler)
      return () => ipcRenderer.removeListener('bazar:cuentas-changed', handler)
    },
  },
  assets: {
    logoDataUrl: (absPath) => ipcRenderer.invoke('assets:logoDataUrl', absPath),
    imageFileDataUrl: (absPath) => ipcRenderer.invoke('assets:imageFileDataUrl', absPath),
  },
  db: {
    getProducts: (filters) => ipcRenderer.invoke('db:getProducts', filters),
    checkRequiredTagsForProduct: (map) => ipcRenderer.invoke('db:checkRequiredTagsForProduct', map),
    addProduct: (product) => ipcRenderer.invoke('db:addProduct', product),
    updateProduct: (product) => ipcRenderer.invoke('db:updateProduct', product),
    deleteProduct: (id) => ipcRenderer.invoke('db:deleteProduct', id),
    searchProducts: (query) => ipcRenderer.invoke('db:searchProducts', query),
    nextCodigoMsr: () => ipcRenderer.invoke('db:nextCodigoMsr'),
    getMonserratDbPath: () => ipcRenderer.invoke('db:getMonserratDbPath'),
    resetToFactorySeed: () => ipcRenderer.invoke('db:resetToFactorySeed'),
    getTagGroupsForProduct: () => ipcRenderer.invoke('db:getTagGroupsForProduct'),
    getProductById: (id) => ipcRenderer.invoke('db:getProductById', id),
    getProductByCodigo: (codigo) => ipcRenderer.invoke('db:getProductByCodigo', codigo),
    getInventoryList: (filters) => ipcRenderer.invoke('db:getInventoryList', filters),
    getTagLabelsForMap: (map) => ipcRenderer.invoke('db:getTagLabelsForMap', map),
    suggestNombreFromTags: (payload) => ipcRenderer.invoke('db:suggestNombreFromTags', payload),
    getNombreEtiquetaDesdeTags: (payload) => ipcRenderer.invoke('db:getNombreEtiquetaDesdeTags', payload),
    suggestPrecioFromTags: (payload) => ipcRenderer.invoke('db:suggestPrecioFromTags', payload),
    getReferenceRows: (payload) => ipcRenderer.invoke('db:getReferenceRows', payload),
    getReferenceSnapshot: (payload) => ipcRenderer.invoke('db:getReferenceSnapshot', payload),
    getSales: (filters) => ipcRenderer.invoke('db:getSales', filters),
    getVentaDetalle: (ventaId) => ipcRenderer.invoke('db:getVentaDetalle', ventaId),
    addSale: (sale) => ipcRenderer.invoke('db:addSale', sale),
    getVentaItemPorCodigoDevolucion: (codigo) => ipcRenderer.invoke('db:getVentaItemPorCodigoDevolucion', codigo),
    registrarDevolucionRapida: (payload) => ipcRenderer.invoke('db:registrarDevolucionRapida', payload),
    findIntercambiableByCodigo: (payload) => ipcRenderer.invoke('db:findIntercambiableByCodigo', payload ?? {}),
    searchIntercambiableCandidates: (payload) =>
      ipcRenderer.invoke('db:searchIntercambiableCandidates', payload ?? {}),
    addIntercambio: (payload) => ipcRenderer.invoke('db:addIntercambio', payload ?? {}),
    scanBanquetaSalidaResult: (payload) => ipcRenderer.invoke('db:scanBanquetaSalidaResult', payload ?? {}),
    listStaleForBanqueta: (opts) => ipcRenderer.invoke('db:listStaleForBanqueta', opts ?? {}),
    suggestByTags: (tags) => ipcRenderer.invoke('db:suggestByTags', tags),
    getWelcomeSnapshot: () => ipcRenderer.invoke('db:getWelcomeSnapshot'),
    getBanquetaSidebarSnapshot: () => ipcRenderer.invoke('db:getBanquetaSidebarSnapshot'),
    listBanquetaSalidas: () => ipcRenderer.invoke('db:listBanquetaSalidas'),
    getActiveBanquetaSalida: () => ipcRenderer.invoke('db:getActiveBanquetaSalida'),
    createBanquetaSalida: (payload) => ipcRenderer.invoke('db:createBanquetaSalida', payload),
    updateBanquetaSalida: (payload) => ipcRenderer.invoke('db:updateBanquetaSalida', payload),
    getBanquetaSalidaDetail: (id) => ipcRenderer.invoke('db:getBanquetaSalidaDetail', id),
    addProductToBanquetaSalida: (payload) => ipcRenderer.invoke('db:addProductToBanquetaSalida', payload),
    removeBanquetaSalidaItem: (itemId) => ipcRenderer.invoke('db:removeBanquetaSalidaItem', itemId),
    setBanquetaSalidaItemResult: (payload) => ipcRenderer.invoke('db:setBanquetaSalidaItemResult', payload),
    activateBanquetaSalida: (id) => ipcRenderer.invoke('db:activateBanquetaSalida', id),
    closeBanquetaSalida: (id) => ipcRenderer.invoke('db:closeBanquetaSalida', id),
    deleteBanquetaSalida: (id) => ipcRenderer.invoke('db:deleteBanquetaSalida', id),
    reorderBanquetaSalidaItems: (payload) => ipcRenderer.invoke('db:reorderBanquetaSalidaItems', payload),
    removeBanquetaSalidaItemsBulk: (itemIds) => ipcRenderer.invoke('db:removeBanquetaSalidaItemsBulk', itemIds),
    previewPriceAdjust: (payload) => ipcRenderer.invoke('db:previewPriceAdjust', payload),
    applyPriceAdjust: (payload) => ipcRenderer.invoke('db:applyPriceAdjust', payload),
    getReferencePatternStats: (payload) => ipcRenderer.invoke('db:getReferencePatternStats', payload),
    getCuadernoTagGroups: () => ipcRenderer.invoke('db:getCuadernoTagGroups'),
    getTagCatalogForManager: () => ipcRenderer.invoke('db:getTagCatalogForManager'),
    cuadernoRenameTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoRenameTagGroup', payload),
    cuadernoDeleteTagOption: (payload) => ipcRenderer.invoke('db:cuadernoDeleteTagOption', payload),
    cuadernoDeleteTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoDeleteTagGroup', payload),
    countProductsByTagOption: (optionId) => ipcRenderer.invoke('db:countProductsByTagOption', optionId),
    listPriceRulesAdmin: () => ipcRenderer.invoke('db:listPriceRulesAdmin'),
    cuadernoAddTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoAddTagGroup', payload),
    cuadernoAddTagOption: (payload) => ipcRenderer.invoke('db:cuadernoAddTagOption', payload),
    cuadernoBulkAddTagOptions: (payload) => ipcRenderer.invoke('db:cuadernoBulkAddTagOptions', payload),
    cuadernoMoveTagOption: (payload) => ipcRenderer.invoke('db:cuadernoMoveTagOption', payload),
    cuadernoRenameTagOption: (payload) => ipcRenderer.invoke('db:cuadernoRenameTagOption', payload),
    cuadernoSetTagOptionActive: (payload) => ipcRenderer.invoke('db:cuadernoSetTagOptionActive', payload),
    cuadernoSetTagGroupStyle: (payload) => ipcRenderer.invoke('db:cuadernoSetTagGroupStyle', payload),
    cuadernoSetTagOptionStyle: (payload) => ipcRenderer.invoke('db:cuadernoSetTagOptionStyle', payload),
    cuadernoReorderTagGroups: (payload) => ipcRenderer.invoke('db:cuadernoReorderTagGroups', payload),
    cuadernoUpsertPriceRule: (payload) => ipcRenderer.invoke('db:cuadernoUpsertPriceRule', payload),
    cuadernoDeletePriceRule: (payload) => ipcRenderer.invoke('db:cuadernoDeletePriceRule', payload),
    listTagPriceRulesSummary: () => ipcRenderer.invoke('db:listTagPriceRulesSummary'),
    listTagPriceRulesForCuaderno: () => ipcRenderer.invoke('db:listTagPriceRulesForCuaderno'),
    setTagOptionPriceRule: (payload) => ipcRenderer.invoke('db:setTagOptionPriceRule', payload),
    getPriceCombosForAnchor: (payload) => ipcRenderer.invoke('db:getPriceCombosForAnchor', payload),
    replacePriceCombosForAnchor: (payload) => ipcRenderer.invoke('db:replacePriceCombosForAnchor', payload),
    listInvPricingRules: () => ipcRenderer.invoke('db:listInvPricingRules'),
    listInvRuleCustomFieldsFlat: () => ipcRenderer.invoke('db:listInvRuleCustomFieldsFlat'),
    getInvPricingRule: (payload) => ipcRenderer.invoke('db:getInvPricingRule', payload),
    findApplicableInvRulePrice: (payload) => ipcRenderer.invoke('db:findApplicableInvRulePrice', payload),
    detectInvRuleCandidate: (payload) => ipcRenderer.invoke('db:detectInvRuleCandidate', payload),
    appendInvRuleRow: (payload) => ipcRenderer.invoke('db:appendInvRuleRow', payload),
    countSimilarProducts: (payload) => ipcRenderer.invoke('db:countSimilarProducts', payload),
    updateInvRuleRowPrice: (payload) => ipcRenderer.invoke('db:updateInvRuleRowPrice', payload),
    upsertInvPricingRule: (payload) => ipcRenderer.invoke('db:upsertInvPricingRule', payload),
    deleteInvPricingRule: (payload) => ipcRenderer.invoke('db:deleteInvPricingRule', payload),
  },
  saldos: {
    listCuentas: (opts) => ipcRenderer.invoke('saldos:listCuentas', opts ?? {}),
    buscarParecidos: (payload) => ipcRenderer.invoke('saldos:buscarParecidos', payload ?? {}),
    crearCliente: (payload) => ipcRenderer.invoke('saldos:crearCliente', payload ?? {}),
    actualizarCliente: (payload) => ipcRenderer.invoke('saldos:actualizarCliente', payload ?? {}),
    setArchivada: (payload) => ipcRenderer.invoke('saldos:setArchivada', payload ?? {}),
    eliminarCliente: (payload) => ipcRenderer.invoke('saldos:eliminarCliente', payload ?? {}),
    registrarMovimientos: (payload) => ipcRenderer.invoke('saldos:registrarMovimientos', payload ?? {}),
    anularMovimiento: (payload) => ipcRenderer.invoke('saldos:anularMovimiento', payload ?? {}),
    elegirImagenId: () => ipcRenderer.invoke('saldos:elegirImagenId'),
    crearRecordatorio: (payload) => ipcRenderer.invoke('saldos:crearRecordatorio', payload ?? {}),
    completarRecordatorio: (payload) => ipcRenderer.invoke('saldos:completarRecordatorio', payload ?? {}),
    eliminarRecordatorio: (payload) => ipcRenderer.invoke('saldos:eliminarRecordatorio', payload ?? {}),
  },
  ledger: {
    query: (opts) => ipcRenderer.invoke('ledger:query', opts ?? {}),
    stats: () => ipcRenderer.invoke('ledger:stats'),
    append: (evt) => ipcRenderer.invoke('ledger:append', evt ?? {}),
  },
  reportes: {
    exportarPdf: (payload) => ipcRenderer.invoke('reportes:exportarPdf', payload ?? {}),
    exportarCsv: (payload) => ipcRenderer.invoke('reportes:exportarCsv', payload ?? {}),
  },
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    set: (patch) => ipcRenderer.invoke('settings:set', patch),
    pickLabelPdfFolder: () => ipcRenderer.invoke('settings:pickLabelPdfFolder'),
  },
  printers: {
    list: () => ipcRenderer.invoke('printers:list'),
    diagnostic: () => ipcRenderer.invoke('printers:diagnostic'),
    testPrint: (printerName) => ipcRenderer.invoke('printers:testPrint', { printerName }),
    printLabel: (payload) => ipcRenderer.invoke('printers:printLabel', payload),
    printTicket: (payload) => ipcRenderer.invoke('printers:printTicket', payload),
  },
  banqueta: {
    printSheet: (detail) => ipcRenderer.invoke('banqueta:printSheet', { detail }),
  },
  shell: {
    openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  },
  labels: {
    list: () => ipcRenderer.invoke('labels:list'),
    getActive: () => ipcRenderer.invoke('labels:getActive'),
    upsert: (template) => ipcRenderer.invoke('labels:upsert', template),
    remove: (id) => ipcRenderer.invoke('labels:remove', id),
    setActive: (id) => ipcRenderer.invoke('labels:setActive', id),
    duplicate: (id) => ipcRenderer.invoke('labels:duplicate', id),
    restoreDefault: () => ipcRenderer.invoke('labels:restoreDefault'),
  },
  productImage: {
    pick: () => ipcRenderer.invoke('productImage:pick'),
  },
  tagIconImage: {
    pick: () => ipcRenderer.invoke('tagIconImage:pick'),
  },
  clientImage: {
    pick: () => ipcRenderer.invoke('clientImage:pick'),
  },
  devices: {
    open: () => ipcRenderer.invoke('devices:open'),
  },
  window: {
    isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('window:maximizeToggle'),
    close: () => ipcRenderer.invoke('window:close'),
    openPdvWindow: () => ipcRenderer.invoke('window:openPdv'),
    /** Ajusta el tamaño del lienzo al shell (cajita); evita “marco” vacío alrededor en Win/Linux. */
    setShellSize: (size) => ipcRenderer.invoke('window:setShellSize', size),
    setWelcomeMode: (compact) => ipcRenderer.invoke('window:setWelcomeMode', Boolean(compact)),
    onState: (callback) => {
      const handler = (_event, state) => {
        if (typeof callback === 'function') callback(state)
      }
      ipcRenderer.on('window:state', handler)
      return () => ipcRenderer.removeListener('window:state', handler)
    },
  },
})
